<a href="https://colab.research.google.com/github/lauritaplavi/Clonaci-n-de-google/blob/main/Actividad3BDManipulacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE: Laura Plascencia Villalobos
*   MATRÍCULA: A01621031

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [45]:
pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.13/dist-packages (1.2.3)

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [87]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [88]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine(
    'mysql+pymysql://mnaTC5053User:mnaTC5053Pass!@20.127.169.219:3306/Netflix',
    pool_recycle=3600,
    pool_size=1,       # Asigna máximo 1 conexión activa por tu sesión
    max_overflow=0     # Impide crear conexiones adicionales secundarias
)
conn = db.connect()

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
query = sqla.text("""
  SELECT ---
  FROM ---
  WHERE ---
""")
pd.read_sql(query, conn)
```

1.	Extrae toda la información de las películas que duran más de 5 horas.

In [49]:
#películas con duración mayor a 5 horas = 300 minutos
query_1 = sqla.text("""
    SELECT *
    FROM movie
    WHERE runtime > 300;
""")

df_1= pd.read_sql(query_1, conn)
df_1

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`? La consulta SQL debe entregar directamente el porcentaje final. No se deben devolver resultados parciales para realizar el cálculo en Python.

In [50]:
query_2 = sqla.text("""
    SELECT
        (SUM(CASE WHEN available_globally = 0 LIKE '%US%' THEN 1 ELSE 0 END) * 100.0) / COUNT(*) AS porcentaje_exclusivo_us
    FROM movie
    WHERE available_globally IS NOT NULL;
""")

df_2 = pd.read_sql(query_2, conn)
df_2

   porcentaje_exclusivo_us
0                 83.57175

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas?
* ¿Cuántos registros tienen el campo `locale` con valor `NULL`? (NULL en SQL ⇔ None en Python)

In [51]:
query_3a = sqla.text("""
    SELECT DISTINCT locale
    FROM movie
""")
df_3a = pd.read_sql(query_3a, conn)

query_3b = sqla.text("""
    SELECT COUNT(*) AS total_null_locale
    FROM movie
    WHERE locale IS NULL
""")
df_3b = pd.read_sql(query_3b, conn)

print("Locales distintos:")
display(df_3a)
print("Total de NULLs en locale:")
display(df_3b)

Locales distintos:

  locale
0   None
1     en

Total de NULLs en locale:

   total_null_locale
0              11255

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).
*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

In [52]:

query_4 = sqla.text("""
    SELECT COUNT(*) AS total_diferentes
    FROM movie
    WHERE title <> original_title
""")
df_4 = pd.read_sql(query_4, conn)
display(df_4)

query_4_detalle = sqla.text("""
    SELECT title, original_title, locale
    FROM movie
    WHERE locale IS NULL AND title = original_title
""")
df_4_detalle = pd.read_sql(query_4_detalle, conn)
display(df_4_detalle.head())

   total_diferentes
0              3947

                            title                  original_title locale
0                  Recep Ivedik 7                  Recep İvedik 7   None
1                        Veronica                        Verónica   None
2                        Fantomas                        Fantômas   None
3  Luccas Neto em: O Hotel Magico  Luccas Neto em: O Hotel Mágico   None
4            Un Dia En El Paraiso            Un día en el paraíso   None

La suposición no es completamente válida, ya que el hecho de que un título no cambie respecto al original no garantiza que la película sea originalmente en inglés o tenga un locale definido.

5.	Determina el título de la película que ha permanecido más tiempo en el top 10.

In [53]:
query_5 = sqla.text("""
    SELECT m.title, v.cumulative_weeks_in_top10
    FROM movie m
    JOIN view_summary v ON m.id = v.movie_id
    ORDER BY v.cumulative_weeks_in_top10 DESC
    LIMIT 1;
""")

df_5 = pd.read_sql(query_5, conn)
df_5

           title  cumulative_weeks_in_top10
0  The Boss Baby                         22

6.	Identifica los 5 programas de TV con mayor cantidad de temporadas.

In [54]:
query_6 = sqla.text("""
    SELECT
        t.title,
        COUNT(s.id) AS num_seasons
    FROM tv_show t
    JOIN season s ON t.id = s.tv_show_id
    GROUP BY t.id, t.title
    ORDER BY num_seasons DESC
    LIMIT 5
""")
df_6 = pd.read_sql(query_6, conn)
df_6

                               title  num_seasons
0                     Grey's Anatomy           20
1                   Naruto Shippuden           20
2                   Heartland (2007)           17
3  It's Always Sunny in Philadelphia           16
4                               NCIS           15

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [89]:
query_7 = sqla.text("""
    SELECT DISTINCT start_date, end_date, duration
    FROM view_summary
    WHERE LOWER(duration) LIKE '%semi%'
       OR LOWER(duration) LIKE '%semes%'
    ORDER BY start_date ASC
""")
df_7 = pd.read_sql(query_7, conn)

df_7

   start_date    end_date       duration
0  2023-07-01  2023-12-31  SEMI_ANNUALLY
1  2024-01-01  2024-06-30  SEMI_ANNUALLY

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

In [59]:
query_8 = sqla.text("""
    SELECT
        s.season_number,
        s.title AS season_title,
        v.views
    FROM tv_show t
    JOIN season s ON t.id = s.tv_show_id
    JOIN view_summary v ON s.id = v.season_id
    WHERE t.title LIKE '%Grey%Anatomy%'
      AND v.start_date >= '2024-01-01'
      AND v.end_date <= '2024-06-30'
    ORDER BY v.views DESC
""")
df_8 = pd.read_sql(query_8, conn)
df_8

    season_number               season_title    views
0               1   Grey's Anatomy: Season 1  3600000
1               2   Grey's Anatomy: Season 2  3100000
2               3   Grey's Anatomy: Season 3  2900000
3               5   Grey's Anatomy: Season 5  2900000
4               4   Grey's Anatomy: Season 4  2900000
5               6   Grey's Anatomy: Season 6  2800000
6               7   Grey's Anatomy: Season 7  2700000
7               8   Grey's Anatomy: Season 8  2600000
8               9   Grey's Anatomy: Season 9  2500000
9              10  Grey's Anatomy: Season 10  2400000
10             11  Grey's Anatomy: Season 11  2200000
11             12  Grey's Anatomy: Season 12  2000000
12             13  Grey's Anatomy: Season 13  2000000
13             14  Grey's Anatomy: Season 14  2000000
14             19  Grey's Anatomy: Season 19  2000000
15             15  Grey's Anatomy: Season 15  1900000
16             16  Grey's Anatomy: Season 16  1800000
17             18  Grey's Anatomy: Season 18  1700000
18             17  Grey's Anatomy: Season 17  1700000
19             20  Grey's Anatomy: Season 20   100000

Según los resultados obtenidos, las primeras temporadas registran la mayor cantidad de visualizaciones en el primer semestre de 2024 (liderando la Temporada 1 con 3.6 millones), observándose una tendencia decreciente conforme se avanza hacia las temporadas más recientes.

Lo que sugiere un comportamiento de retención, donde nuevos usuarios descubren o reviven la serie desde sus inicios, pero no todos llegan a las temporadas posteriores. Asimismo, la caída drástica observada en la Temporada 20 (100,000 vistas) puede estar directamente ligada a su fecha de incorporación o lanzamiento en la plataforma, disponiendo de un menor tiempo de exposición durante el periodo evaluado en comparación con el resto del catálogo.

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [60]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [61]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [62]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [63]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

In [64]:
greys = tv_show[tv_show['title'].str.contains("Grey's Anatomy", case=False, na=False)]
greys_seasons = pd.merge(greys, season, left_on='id', right_on='tv_show_id', suffixes=('_show', '_season'))

views_2024_h1 = view_summary[
    (pd.to_datetime(view_summary['start_date']) >= '2024-01-01') &
    (pd.to_datetime(view_summary['end_date']) <= '2024-06-30')
]

df_pandas_res = pd.merge(greys_seasons, views_2024_h1, left_on='id_season', right_on='season_id')
df_pandas_res = df_pandas_res[['season_number', 'title_season', 'views']].sort_values(by='views', ascending=False)
df_pandas_res = df_pandas_res.rename(columns={'title_season': 'season_title'})
df_pandas_res.reset_index(drop=True, inplace=True)
df_pandas_res

    season_number               season_title    views
0             1.0   Grey's Anatomy: Season 1  3600000
1             2.0   Grey's Anatomy: Season 2  3100000
2             3.0   Grey's Anatomy: Season 3  2900000
3             5.0   Grey's Anatomy: Season 5  2900000
4             4.0   Grey's Anatomy: Season 4  2900000
5             6.0   Grey's Anatomy: Season 6  2800000
6             7.0   Grey's Anatomy: Season 7  2700000
7             8.0   Grey's Anatomy: Season 8  2600000
8             9.0   Grey's Anatomy: Season 9  2500000
9            10.0  Grey's Anatomy: Season 10  2400000
10           11.0  Grey's Anatomy: Season 11  2200000
11           12.0  Grey's Anatomy: Season 12  2000000
12           13.0  Grey's Anatomy: Season 13  2000000
13           14.0  Grey's Anatomy: Season 14  2000000
14           19.0  Grey's Anatomy: Season 19  2000000
15           15.0  Grey's Anatomy: Season 15  1900000
16           16.0  Grey's Anatomy: Season 16  1800000
17           18.0  Grey's Anatomy: Season 18  1700000
18           17.0  Grey's Anatomy: Season 17  1700000
19           20.0  Grey's Anatomy: Season 20   100000

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [65]:

employees_ref = db.collection('EMPLOYEE')
docs = employees_ref.stream()

employees_data = []
for doc in docs:
    data = doc.to_dict()
    data['id'] = doc.id
    employees_data.append(data)

df_employees = pd.DataFrame(employees_data)
display(df_employees)

  emp_fname   emp_lname                    id              emp_hiredate
0     David      Senior  8LcLuxVHGAd2d9IQc5jF 1989-07-12 06:00:00+00:00
1   William  Smithfield  Fzd60D6Z2CU4n0wVV8YN 2004-06-04 05:00:00+00:00
2      John        News  lX5xuQ5w3i6ib2ExccWY 2000-11-08 06:00:00+00:00
3      June     Arbough  yocFj2lichOkbAj9NBfp 1996-12-01 06:00:00+00:00

In [66]:
firebase_admin.delete_app(firebase_admin.get_app())

---

**Declaración de uso de IA**

Si aplica, deberá indicarse la herramienta y el modelo empleado en la entrega, así como la finalidad de su uso (generación de código / depuración / optimización).

Por ejemplo:

*   OpenAI. (2026). ChatGPT (basado en GPT-4) [Modelo de lenguaje grande], utilizado para resolver porblemas de conexión con el motor de busqueda y en el inciso 10 mejora del código para hacerlo más eficiente con un ciclo. https://chat.openai.com/

---